const $=id=>document.getElementById(id);let state={ratio:'1:1',text:'오늘의 작은 발견\n내일의 새로운 시작',fontSize:76,color:'#ffffff',position:'bottom',align:'left',fit:'cover',background:'#171922',scrim:true,image:null};let image=null;
const sizes={'1:1':[1080,1080],'4:5':[1080,1350],'9:16':[1080,1920]};
function notify(msg,error=false){$('notice').textContent=msg;$('notice').dataset.error=error}
function sampleImage(){const c=document.createElement('canvas');c.width=1200;c.height=1500;const x=c.getContext('2d');const g=x.createLinearGradient(0,0,1200,1500);g.addColorStop(0,'#5377d8');g.addColorStop(.52,'#7861a4');g.addColorStop(1,'#de754a');x.fillStyle=g;x.fillRect(0,0,c.width,c.height);x.strokeStyle='#ffffff33';x.lineWidth=2;for(let i=0;i<8;i++){x.beginPath();x.ellipse(610,700,180+i*70,260+i*50,.5,0,Math.PI*2);x.stroke()}return c.toDataURL('image/png')}
async function decode(src){const i=new Image();i.src=src;await i.decode();return i}
async function useImage(src){const next=await decode(src);image=next;state.image=src;render()}
function render(){const c=$('preview'),[w,h]=sizes[state.ratio];c.width=w;c.height=h;const x=c.getContext('2d');x.fillStyle=state.background;x.fillRect(0,0,w,h);if(image){const scale=state.fit==='cover'?Math.max(w/image.width,h/image.height):Math.min(w/image.width,h/image.height);const iw=image.width*scale,ih=image.height*scale;x.drawImage(image,(w-iw)/2,(h-ih)/2,iw,ih)}const pad=72;let fs=state.fontSize;x.font=`700 ${fs}px "Malgun Gothic","Segoe UI",sans-serif`;const lines=state.text.split('\n');const lh=fs*1.35,total=lines.length*lh;const y=state.position==='top'?pad:state.position==='center'?(h-total)/2:h-pad-total;if(state.scrim&&state.text.trim()){const g=x.createLinearGradient(0,y-pad,0,y+total+pad);g.addColorStop(0,'#0000');g.addColorStop(.4,'#0009');g.addColorStop(1,'#000b');x.fillStyle=g;x.fillRect(0,y-pad,w,total+pad*2)}x.fillStyle=state.color;x.textBaseline='top';x.textAlign=state.align;const tx=state.align==='left'?pad:state.align==='right'?w-pad:w/2;lines.forEach((line,i)=>x.fillText(line,tx,y+i*lh));$('dimensions').textContent=`${w} × ${h} px`;$('sizeValue').textContent=state.fontSize}
function bind(){for(const id of ['text','fontSize','position','align','fit','background','scrim','textColor']){$(id).addEventListener('input',()=>{const k=id==='textColor'?'color':id;state[k]=id==='scrim'?$(id).checked:id==='fontSize'?Number($(id).value):$(id).value;render()})}document.querySelectorAll('[data-ratio]').forEach(b=>b.onclick=()=>{state.ratio=b.dataset.ratio;document.querySelectorAll('[data-ratio]').forEach(v=>v.setAttribute('aria-pressed',v===b));render()});$('sample').onclick=()=>useImage(sampleImage());$('removeImage').onclick=()=>{image=null;state.image=null;render()};$('download').onclick=()=>{const a=document.createElement('a');a.download=`frame-lab-${state.ratio.replace(':','x')}.png`;a.href=$('preview').toDataURL('image/png');a.click()};$('imageFile').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{if(!['image/png','image/jpeg'].includes(f.type))throw Error('PNG·JPEG 파일만 지원합니다. 기존 작업은 유지됩니다.');if(f.size>8*1024*1024)throw Error('최대 8MB까지 불러올 수 있습니다.');const reader=new FileReader();const data=await new Promise((r,j)=>{reader.onload=()=>r(reader.result);reader.onerror=j;reader.readAsDataURL(f)});const next=await decode(data);if(next.width*next.height>20000000)throw Error('이미지는 최대 2천만 픽셀까지 지원합니다.');const c=document.createElement('canvas');c.width=next.width;c.height=next.height;c.getContext('2d').drawImage(next,0,0);await useImage(c.toDataURL('image/png'));$('imageInfo').textContent=`${next.width} × ${next.height} · 메타데이터 제거 후 사용`;notify('이미지를 불러왔습니다.')}catch(err){notify(err.message||'이미지를 읽을 수 없습니다. 기존 작업을 유지합니다.',true)}e.target.value=''}}
bind();$('text').value=state.text;await useImage(sampleImage());
